//
//  RetrievalParams.swift
//
//
//  Created by Marcos Alba on 9/1/24.
//

import Foundation

/**
 Parmas needed for a retrieval
 */
public struct RetrievalParams {
    internal let accessToken: String
    internal let citiboxId: Int
    internal let isSandbox: Bool
    internal let debug: Bool

    /// Initializes the `RetrievalParams` with the needed data.
    ///
    /// - Parameters:
    ///   - accessToken: Mandatory. String. Access token provided via oauth for Citibox server to the Carrier server. Important: The carrier app should never contact the citibox server directly.
    ///   - citiboxId: Mandatory. Int. ID for the Citibox transaction to be collected. The citiboxId value is generated by Citibox during a delivery through Deeplink.
    ///   - sandbox: Optional. Bool. Tells if using sandbox environment. False by default.
    ///   - debug: Optional. Bool. Shows a different view in order to be able to debug the delivery. Is intended to be used when we face some issue that cannot understand or we want to verify params or UI. False by default.
    public init(accessToken: String, citiboxId: Int, sandbox: Bool = false, debug: Bool = false) {
        self.accessToken = accessToken
        self.citiboxId = citiboxId
        self.isSandbox = sandbox
        self.debug = debug
    }
}
